---
title: "Analysis of Mean Annual Fluxes and Storages"
output:
  html_notebook: default
  html_document:
    theme: united
    df_print: paged
  pdf_document: default
---

### Load libraries and functions

```{r message=FALSE, warning=FALSE}
source("0_utilities.R")
```

### Import the previously processed data

```{r Import data}
data_annual <- read_csv("../output/data_annual.csv",
                        col_types = list(wy = col_character(),
                                         watershed = col_factor(),
                                         biomass = col_factor()))

diff_flux_annual <- read_rds("../output/diff_flux_annual.rds")
diff_storage_annual <- read_rds("../output/diff_storage_annual.rds")
```


### Group annual data into mean annual data

```{r}
data_mean_annual <- data_annual %>% 
    dplyr::select(-wy) %>% 
  dplyr::group_by(watershed, biomass) %>% 
  dplyr::summarise_all(mean)
```

***
### Plot mean annual flux data

```{r, results='hide'}

mean_annual_fig <- function(data, var){
  x <- ggplot(data) +
    geom_col(aes_string(x="biomass", y=var)) +
    facet_grid(.~watershed) +
    labs(title=var) +
    NULL
  return(x)
}

purrr::map(flux_var, mean_annual_fig, data=data_mean_annual)
```

***
### Plot mean annual storage data

```{r message=FALSE, results='hide'}

purrr::map(storage_var, mean_annual_fig, data=data_mean_annual)
```







